### ISSUE TITLE
bug: commit hook fails even though the commit messages and linter checks pass

### ISSUE THREAD

**Issue by mertkaya1033** [acikkaynak/deprem-yardim-frontend#1009]
## Bug Definition
Commit hook fails even though the commit messages and linter checks pass.

-- Please add discord contact information
** discord username: Sertcast#8543 **

## Describe how you are producing the bug step by step
Commit staged change that normally passes all checks.

## Expected Behaviour
Commit should not fail.

## Screen shots
```
0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/lib/node_modules/npm/bin/npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--no-yes',
0 verbose cli   '--',
0 verbose cli   'commitlint',
0 verbose cli   '--edit',
0 verbose cli   '.git/COMMIT_EDITMSG'
0 verbose cli ]
1 info using npm@8.5.5
2 info using node@v16.15.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/Users/mert/projects/deprem-yardim-frontend/.npmrc Completed in 2ms
10 timing config:load:project Completed in 4ms
11 timing config:load:file:/Users/mert/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 2ms
14 timing config:load:global Completed in 2ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 13ms
19 timing npm:load:configload Completed in 13ms
20 timing npm:load:setTitle Completed in 17ms
21 timing config:load:flatten Completed in 2ms
22 timing npm:load:display Completed in 4ms
23 verbose logfile /Users/mert/.npm/_logs/2023-02-15T07_59_32_225Z-debug-0.log
24 timing npm:load:logFile Completed in 4ms
25 timing npm:load:timers Completed in 0ms
26 timing npm:load:configScope Completed in 0ms
27 timing npm:load Completed in 39ms
28 silly logfile start cleaning logs, removing 1 files
29 http fetch GET 200 https://registry.npmjs.org/commitlint 163ms (cache revalidated)
30 timing arborist:ctor Completed in 0ms
31 timing arborist:ctor Completed in 0ms
32 timing command:exec Completed in 995ms
33 verbose stack Error: canceled
33 verbose stack     at exec (/usr/local/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:156:17)
33 verbose stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:66:5)
34 verbose cwd /Users/mert/projects/deprem-yardim-frontend
35 verbose Darwin 22.2.0
36 verbose argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "exec" "--no-yes" "--" "commitlint" "--edit" ".git/COMMIT_EDITMSG"
37 verbose node v16.15.0
38 verbose npm  v8.5.5
39 error canceled
40 verbose exit 1
41 timing npm Completed in 1212ms
42 verbose code 1
43 error A complete log of this run can be found in:
43 error     /Users/mert/.npm/_logs/2023-02-15T07_59_32_225Z-debug-0.log
```

**Comment by absolutezero13** [comment]
`npm install -g @commitlint/cli @commitlint/config-conventional` 

Can you try after this?

**Comment by CyhnYldz** [comment]
I don't think this waiting-test label is about us but I will change the label to test-fail to help with necessary attention. please let us know if it is an un-necessary label change so we can change it back to way it is.

**Comment by mertkaya1033** [comment]
> `npm install -g @commitlint/cli @commitlint/config-conventional`
> 
> Can you try after this?

They were already a part of my package.json, and I had called `yarn` to install dependencies. It seems like I messed up my local configs somehow where I kept getting an error. I did a fresh `git clone` and the problem was fixed.
